description: 'YACB: Yet Another Code Blog'
baseURL: 'https://ejosh.co/de/'
languageCode: 'en-us'
title: 'YACB: Yet Another Code Blog'
theme: "joshugo"

sectionPagesMenu: "main"

author:
  name: Joshua Johanan

params:
  name: eJosh.co/de
  

permalinks:
  posts: /:year/:month/:title/

menu:
  main:
    - identifier: "posts"
      weight: 1
      name: "Posts"
      url: "/posts/"
    - identifier: "about-me"
      weight: 2
      name: "About Me"
      url: "/about-me"