description: 'YACB: Yet Another Code Blog'
baseURL: 'https://ejosh.co/de/'
languageCode: 'en-us'
title: 'YACB: Yet Another Code Blog'
theme: "joshugo"

sectionPagesMenu: ""
googleAnalytics: GTM-WRQG68S
disqusShortname: ejoshcode

params:
  name: josh.code
  author:
    name: Joshua Johanan
    gravatar: https://secure.gravatar.com/avatar/24025160393b461e60c21638367caa43
    images:
      - /de/images/josh_patch.webp
      - https://secure.gravatar.com/avatar/24025160393b461e60c21638367caa43?s=50
      - /de/images/josh_funko_pop.webp
  

permalinks:
  posts: /:year/:month/:title/

menu:
  main:
    - identifier: "posts"
      weight: 1
      name: "Posts"
      url: "/posts/"
    - identifier: "about-me"
      weight: 2
      name: "About Me"
      url: "/about-me"
  footer:
    - identifier: "posts"
      weight: 1
      name: "Posts"
      url: "/posts/"
    - identifier: "tags"
      weight: 2
      name: "Tags"
      url: "/tags/"
    - identifier: "categories"
      weight: 3
      name: "Categories"
      url: "/categories/"